### ISSUE TITLE
[[Question]] QA#743198(yaogata)Tell me about getCategoryInfo

### ISSUE THREAD

**Issue by AshisutoSup** [EricomSoftwareLtd/Shield#794]
About shield Logs.
there is a lot of following massages in Shield logs.
getCategoryInfo failed for accounts.google.com:443 service not licensed (402)

Q1: Is it a regarding the categoly

Is it a log related to the category?

Because this error has occurred, it will be detected frequently in the log. Is there a way to prevent this log from being issued?
[temp.txt](https://github.com/EricomSoftwareLtd/Shield/files/3476171/temp.txt)

**Comment by eyalcohenericom** [comment]
@AshisutoSup It is related to the categories.

Looks like you do not have license for categories but Shield is configured to enforce categories or phishing.

So, either it is a mistake that you do not have the license, or please change the settings not to enforce categories & phishing.

**Comment by AshisutoSup** [comment]
miss
