### ISSUE TITLE
[[Investigate]] QA#744973(yaogata) ’Cannot GET /app/kibana/’ from 'Advanced' link

### ISSUE THREAD

**Issue by AshisutoSup** [EricomSoftwareLtd/Shield#814]
In the Control panel, 
  Report-->, "Advanced" link 
dosen't work at the customer environment.
Please tell me what settings are missing
They tried to re start the services already.
------------------------------------------
The error message  
------------------------------------------
Cannot GET /app/kibana/
------------------------------------------

------------------------------------------
resulut　of　/status.sh -a
------------------------------------------
root@poc01-manage01:/usr/local/ericomshield# ./status.sh -a
ID                  NAME                                      MODE                REPLICAS            
IMAGE                                                         PORTS
r1q9ypcax0hl        shield_authproxy                          global              1/1                 
securebrowsing/shield-authproxy:190722-14.37-4630
pd9a325oesa3        shield_cdr-controller                     replicated          1/1                 
securebrowsing/shield-cdr-controller:190721-08.37-4616
iqn8jkf2a0jw        shield_cdr-dispatcher                     replicated          2/2                 
securebrowsing/shield-cdr-dispatcher:190714-07.21-4590
45czeibrwwpn        shield_collector                          global              3/3                 
securebrowsing/shield-collector:190717-11.11-4610
wwlcw2qi6rwb        shield_consul                             replicated          1/1                 
securebrowsing/shield-consul-agent:190624-14.49-4452          *:8500->8500/tcp
436jt2o64hzy        shield_consul-server                      replicated          5/5                 
securebrowsing/shield-configuration:190314-08.02-3983
n1244aam09rb        shield_dns                                replicated          2/2                 
securebrowsing/shield-dns:190523-19.10-4259
ieyc09na7ia8        shield_elk                                replicated          1/1                 
securebrowsing/shield-elk:190325-13.42-4039
lckckf8voqrl        shield_es-core-sync                       replicated          1/1                 
securebrowsing/es-core-sync:190714-05.44-4589
ogjkjvm6n098        shield_es-file-preview                    replicated          1/1                 
securebrowsing/es-file-preview:190715-05.43-4596
camlo3w5ds76        shield_es-ldap-proxy                      replicated          1/1                 
securebrowsing/es-ldap-proxy:190725-13.40-4647
9f04k2nmnd3m        shield_es-license-manager                 replicated          1/1                 
securebrowsing/es-license-manager:190707-14.07-4532
t02dcbta2zdl        shield_es-policy-manager                  replicated          2/2                 
securebrowsing/es-policy-manager:190721-12.52-4617
pmiu66txb9ge        shield_es-proxy-egress                    replicated          2/2                 
securebrowsing/es-proxy-egress:190707-13.18-4529
6dm9xcr2ihhp        shield_es-remote-browser-scaler           replicated          1/1                 
securebrowsing/es-remote-browser-scaler:190707-14.07-4532
419udkaj642o        shield_es-system-configuration            replicated          1/1                 
securebrowsing/es-system-configuration:190722-11.11-4628
nltr07kq86r5        shield_es-system-monitor                  replicated          1/1                 
securebrowsing/es-system-monitor:190801-09.13-4660
yqyga1bwzj7t        shield_ext-proxy                          replicated          2/2                 
securebrowsing/extproxy:190723-16.12-4643
xzt1dh8c9lux        shield_ext-proxy-noadblock                replicated          2/2                 
securebrowsing/extproxy:190723-16.12-4643
ee3shz9e86vt        shield_icap-server                        replicated          2/2                 
securebrowsing/icap-server:190801-09.50-4662
yfjd7t8md8sl        shield_logspout                           global              3/3                 
securebrowsing/shield-logspout:171123-17.23-642
6dv5cjgdoicl        shield_maintenance                        global              3/3                 
securebrowsing/shield-maintenance:181029-09.26-3074
1sjzq5rpwz87        shield_netdata                            global              1/1                 
securebrowsing/netdata:180114-08.17-1026                      *:8383->19999/tcp
41qscx8dp2nb        shield_notifier                           replicated          1/1                 
securebrowsing/shield-notifier:190707-14.07-4532
wr09zdb3hzaw        shield_portainer                          replicated          1/1                 
securebrowsing/shield-portainer:180930-11.41-2885             *:9000->9000/tcp
fmavmv4nhl85        shield_portainer_agent                    global              3/3                 
portainer/agent:1.1.2
225yv260xa3u        shield_proxy-server                       replicated          2/2                 
securebrowsing/proxy-server:190717-08.42-4609
2ubyv9lmlj5h        shield_proxyless-connector                replicated          1/1                 
securebrowsing/shield-proxyless-connector:190708-07.41-4539   *:80->80/tcp
ekh4hfo0zkq6        shield_shield-admin                       replicated          1/1                 
securebrowsing/shield-admin:190730-06.52-4652                 *:8181->8181/tcp
n5mh8672v6x1        shield_shield-browser                     replicated          72/72               
securebrowsing/shield-cef:190801-09.13-4660
3rjth8higa2r        shield_shield-browser-20190821005149087   replicated          20/20               
securebrowsing/shield-cef:190801-09.13-4660
vnhykm03ijlo        shield_shield-browser-20190821005219125   replicated          10/10               
securebrowsing/shield-cef:190801-09.13-4660
9dx4tyv47ofc        shield_speedtest                          replicated          1/1                 
securebrowsing/speedtest:181010-18.49-2935                    *:8185->8185/tcp
iqox4wr3za0q        shield_web-service                        replicated          1/1                 
securebrowsing/shield-web-service:190707-14.07-4532
------------------------------------------------------------------------------

Ericom Shield (19.07.1:Build_554) on poc01.oce.ne.jp (172.27.80.10) - Healthy System Status | 
system-health | | healthy: true | | alertsCount: 1 | | alertsSeverity: 1 | | lastUpdate: 
1566350034923 | | lastUpdateStr: Wed, 21 Aug 2019 01:13:54 GMT | license | | date: Sun Sep 01 2019 
12:52:07 GMT+0900 (Japan Standard Time) | | number of licenses: 50 | | licenses in use: 0 | | 
license type:

Thank you.
Yasue Ogata

**Comment by AshisutoSup** [comment]
miss

**Comment by AshisutoSup** [comment]
In the Control panel,
Report-->, "Advanced" link
dosen't work at the customer environment.
Please tell me what settings are missing
They tried to re start the services already.
The error message
Cannot GET /app/kibana/
resulut　of　/status.sh -a
root@poc01-manage01:/usr/local/ericomshield# ./status.sh -a
ID NAME MODE REPLICAS
IMAGE PORTS
r1q9ypcax0hl shield_authproxy global 1/1
securebrowsing/shield-authproxy:190722-14.37-4630
pd9a325oesa3 shield_cdr-controller replicated 1/1
securebrowsing/shield-cdr-controller:190721-08.37-4616
iqn8jkf2a0jw shield_cdr-dispatcher replicated 2/2
securebrowsing/shield-cdr-dispatcher:190714-07.21-4590
45czeibrwwpn shield_collector global 3/3
securebrowsing/shield-collector:190717-11.11-4610
wwlcw2qi6rwb shield_consul replicated 1/1
securebrowsing/shield-consul-agent:190624-14.49-4452 *:8500->8500/tcp
436jt2o64hzy shield_consul-server replicated 5/5
securebrowsing/shield-configuration:190314-08.02-3983
n1244aam09rb shield_dns replicated 2/2
securebrowsing/shield-dns:190523-19.10-4259
ieyc09na7ia8 shield_elk replicated 1/1
securebrowsing/shield-elk:190325-13.42-4039
lckckf8voqrl shield_es-core-sync replicated 1/1
securebrowsing/es-core-sync:190714-05.44-4589
ogjkjvm6n098 shield_es-file-preview replicated 1/1
securebrowsing/es-file-preview:190715-05.43-4596
camlo3w5ds76 shield_es-ldap-proxy replicated 1/1
securebrowsing/es-ldap-proxy:190725-13.40-4647
9f04k2nmnd3m shield_es-license-manager replicated 1/1
securebrowsing/es-license-manager:190707-14.07-4532
t02dcbta2zdl shield_es-policy-manager replicated 2/2
securebrowsing/es-policy-manager:190721-12.52-4617
pmiu66txb9ge shield_es-proxy-egress replicated 2/2
securebrowsing/es-proxy-egress:190707-13.18-4529
6dm9xcr2ihhp shield_es-remote-browser-scaler replicated 1/1
securebrowsing/es-remote-browser-scaler:190707-14.07-4532
419udkaj642o shield_es-system-configuration replicated 1/1
securebrowsing/es-system-configuration:190722-11.11-4628
nltr07kq86r5 shield_es-system-monitor replicated 1/1
securebrowsing/es-system-monitor:190801-09.13-4660
yqyga1bwzj7t shield_ext-proxy replicated 2/2
securebrowsing/extproxy:190723-16.12-4643
xzt1dh8c9lux shield_ext-proxy-noadblock replicated 2/2
securebrowsing/extproxy:190723-16.12-4643
ee3shz9e86vt shield_icap-server replicated 2/2
securebrowsing/icap-server:190801-09.50-4662
yfjd7t8md8sl shield_logspout global 3/3
securebrowsing/shield-logspout:171123-17.23-642
6dv5cjgdoicl shield_maintenance global 3/3
securebrowsing/shield-maintenance:181029-09.26-3074
1sjzq5rpwz87 shield_netdata global 1/1
securebrowsing/netdata:180114-08.17-1026 *:8383->19999/tcp
41qscx8dp2nb shield_notifier replicated 1/1
securebrowsing/shield-notifier:190707-14.07-4532
wr09zdb3hzaw shield_portainer replicated 1/1
securebrowsing/shield-portainer:180930-11.41-2885 *:9000->9000/tcp
fmavmv4nhl85 shield_portainer_agent global 3/3
portainer/agent:1.1.2
225yv260xa3u shield_proxy-server replicated 2/2
securebrowsing/proxy-server:190717-08.42-4609
2ubyv9lmlj5h shield_proxyless-connector replicated 1/1
securebrowsing/shield-proxyless-connector:190708-07.41-4539 *:80->80/tcp
ekh4hfo0zkq6 shield_shield-admin replicated 1/1
securebrowsing/shield-admin:190730-06.52-4652 *:8181->8181/tcp
n5mh8672v6x1 shield_shield-browser replicated 72/72
securebrowsing/shield-cef:190801-09.13-4660
3rjth8higa2r shield_shield-browser-20190821005149087 replicated 20/20
securebrowsing/shield-cef:190801-09.13-4660
vnhykm03ijlo shield_shield-browser-20190821005219125 replicated 10/10
securebrowsing/shield-cef:190801-09.13-4660
9dx4tyv47ofc shield_speedtest replicated 1/1
securebrowsing/speedtest:181010-18.49-2935 *:8185->8185/tcp
iqox4wr3za0q shield_web-service replicated 1/1
securebrowsing/shield-web-service:190707-14.07-4532
Ericom Shield (19.07.1:Build_554) on poc01.oce.ne.jp (172.27.80.10) - Healthy System Status |
system-health | | healthy: true | | alertsCount: 1 | | alertsSeverity: 1 | | lastUpdate:
1566350034923 | | lastUpdateStr: Wed, 21 Aug 2019 01:13:54 GMT | license | | date: Sun Sep 01 2019
12:52:07 GMT+0900 (Japan Standard Time) | | number of licenses: 50 | | licenses in use: 0 | |
license type:

Thank you.
Yasue Ogata

**Comment by TakuyaARITA** [comment]
yaogata > 何がしたいですしか？
https://github.com/EricomSoftwareLtd/Shield-Feedback/issues
こちらに投稿してください。

そして、control planeということばが出てくるのに、status.shがでてきたり、よくわからないことになっています。
一度ちゃんと社内でもんでからGitへいれてください。
